BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ==========================================
-- 1. ACCOUNT & AUTH
-- ==========================================

CREATE TABLE users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    phone_number varchar(15) UNIQUE NOT NULL,
    email varchar(255) UNIQUE,
    password_hash varchar(255),
    role varchar(20) CHECK (role IN ('Customer', 'Worker', 'Admin')),
    avatar_url text,
    is_active boolean DEFAULT true,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE user_social_logins (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES users(id),
    provider varchar(50),
    provider_id varchar(255) NOT NULL,
    created_at timestamptz DEFAULT now(),

    CONSTRAINT uq_user_social_provider UNIQUE (provider, provider_id)
);

CREATE TABLE workers (
    worker_id uuid PRIMARY KEY REFERENCES users(id),
    full_name varchar(100),
    identity_card varchar(20) UNIQUE,
    verification_status varchar(50) DEFAULT 'Unverified'
        CHECK (verification_status IN ('Unverified', 'Pending', 'Approved', 'Rejected')),
    latitude numeric(10,8),
    longitude numeric(11,8),
    is_available boolean DEFAULT false,
    reputation_score numeric(3,1) DEFAULT 5.0
        CHECK (reputation_score >= 0 AND reputation_score <= 5),
    missed_count int DEFAULT 0 CHECK (missed_count >= 0),
    rejection_count int DEFAULT 0 CHECK (rejection_count >= 0),
    rejected_priority_until timestamptz,
    experience_description text,
    service_area varchar(255)
);

CREATE TABLE worker_identity_cards (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    worker_id uuid UNIQUE REFERENCES workers(worker_id),
    front_image_url text,
    back_image_url text,
    vnpt_ekyc_hash varchar(255),
    status varchar(50) DEFAULT 'Pending'
        CHECK (status IN ('Pending', 'Approved', 'Rejected'))
);

CREATE TABLE customers (
    customer_id uuid PRIMARY KEY REFERENCES users(id),
    full_name varchar(100)
);

CREATE TABLE customer_addresses (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id uuid REFERENCES customers(customer_id),
    label varchar(50),
    address text NOT NULL,
    latitude numeric(10,8),
    longitude numeric(11,8),
    is_default boolean DEFAULT false
);

CREATE TABLE otp_codes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    phone_number varchar(15),
    otp_code varchar(6),
    action_type varchar(50)
        CHECK (action_type IN ('Register', 'Forgot_Password', 'Withdraw_Money')),
    expires_at timestamptz,
    is_used boolean DEFAULT false
);

CREATE TABLE refresh_tokens (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES users(id),
    token text NOT NULL,
    expires_at timestamptz NOT NULL,
    is_revoked boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

-- ==========================================
-- 2. SERVICE & SEARCH
-- ==========================================

CREATE TABLE service_categories (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name varchar(255) NOT NULL
);

CREATE TABLE service_items (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_category_id int REFERENCES service_categories(id),
    item_name varchar(255) NOT NULL,
    suggested_price numeric(12,2)
);

CREATE TABLE worker_services (
    worker_id uuid REFERENCES workers(worker_id),
    service_id int REFERENCES service_categories(id),
    base_price numeric(12,2),

    PRIMARY KEY (worker_id, service_id)
);

CREATE TABLE favorite_workers (
    customer_id uuid REFERENCES customers(customer_id),
    worker_id uuid REFERENCES workers(worker_id),
    saved_at timestamptz DEFAULT now(),

    PRIMARY KEY (customer_id, worker_id)
);

-- ==========================================
-- 3. BOOKING, QUOTATION & WARRANTY
-- ==========================================

CREATE TABLE bookings (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id uuid REFERENCES customers(customer_id),
    worker_id uuid REFERENCES workers(worker_id),
    service_id int REFERENCES service_categories(id),
    address text NOT NULL,
    destination_lat numeric(10,8),
    destination_lng numeric(11,8),
    issue_description text,
    scheduled_time timestamptz,
    payment_method varchar(50) DEFAULT 'CASH'
        CHECK (payment_method IN ('CASH', 'BANK_TRANSFER', 'WALLET')),
    final_price numeric(12,2),
    status varchar(50) DEFAULT 'Pending'
        CHECK (
            status IN (
                'Pending',
                'Accepted',
                'Surveying',
                'Waiting_Approval',
                'In_Progress',
                'Completed',
                'Cancelled'
            )
        ),
    created_at timestamptz DEFAULT now()
);

CREATE TABLE booking_worker_assignments (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id uuid REFERENCES bookings(id),
    worker_id uuid REFERENCES workers(worker_id),
    status varchar(50) DEFAULT 'Pending'
        CHECK (status IN ('Pending', 'Accepted', 'Rejected', 'Missed')),
    assigned_at timestamptz DEFAULT now(),
    responded_at timestamptz
);

CREATE TABLE worker_quotations (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    worker_id uuid REFERENCES workers(worker_id),
    booking_id uuid REFERENCES bookings(id),
    total_proposed_price numeric(12,2) NOT NULL,
    status varchar(50) DEFAULT 'Pending'
        CHECK (status IN ('Pending', 'Accepted', 'Rejected')),
    created_at timestamptz DEFAULT now()
);

CREATE TABLE quotation_items (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    quotation_id uuid REFERENCES worker_quotations(id),
    service_item_id int REFERENCES service_items(id),
    item_name varchar(255) NOT NULL,
    quantity int DEFAULT 1 CHECK (quantity > 0),
    unit_price numeric(12,2) NOT NULL,
    total_price numeric(12,2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE proof_of_works (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id uuid REFERENCES bookings(id),
    image_url text NOT NULL,
    proof_type varchar(50)
        CHECK (proof_type IN ('BEFORE_REPAIR', 'AFTER_REPAIR')),
    captured_at timestamptz DEFAULT now()
);

CREATE TABLE cancellation_details (
    booking_id uuid PRIMARY KEY REFERENCES bookings(id),
    cancelled_by_id uuid REFERENCES users(id),
    cancelled_by_role varchar(20)
        CHECK (cancelled_by_role IN ('Customer', 'Worker', 'Admin')),
    reason_category varchar(50),
    cancellation_reason text,
    reputation_penalty_applied numeric(3,1) DEFAULT 0,
    cancelled_at timestamptz DEFAULT now()
);

CREATE TABLE booking_histories (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id uuid REFERENCES bookings(id),
    status_update varchar(50),
    updated_at timestamptz DEFAULT now()
);

CREATE TABLE complaint_warranties (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id uuid UNIQUE REFERENCES bookings(id),
    customer_reason text,
    worker_response text,
    evidence_image_urls text,
    worker_evidence_image_urls text,
    status varchar(50) DEFAULT 'Pending'
        CHECK (status IN ('Pending', 'Worker_Responded', 'Resolved')),
    deadline_to_respond timestamptz,
    created_at timestamptz DEFAULT now()
);

-- ==========================================
-- 4. WALLET & PAYMENT
-- ==========================================

CREATE TABLE worker_wallets (
    worker_id uuid PRIMARY KEY REFERENCES workers(worker_id),
    available_balance numeric(12,2) DEFAULT 0,
    held_balance numeric(12,2) DEFAULT 0,
    debt_balance numeric(12,2) DEFAULT 0,

    CHECK (available_balance >= 0),
    CHECK (held_balance >= 0),
    CHECK (debt_balance >= 0)
);

CREATE TABLE worker_bank_accounts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    worker_id uuid REFERENCES workers(worker_id),
    bank_name varchar(100),
    account_number varchar(50),
    account_name varchar(100),
    is_default boolean DEFAULT true
);

CREATE TABLE transaction_histories (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    wallet_id uuid REFERENCES worker_wallets(worker_id),
    booking_id uuid REFERENCES bookings(id),
    transaction_type varchar(50)
        CHECK (
            transaction_type IN (
                'Deposit',
                'Withdraw',
                'Holding',
                'Release',
                'Fee_Deduction'
            )
        ),
    amount numeric(12,2),
    transaction_code varchar(50) UNIQUE,
    gateway_reference_code varchar(100),
    target_bank_account_id uuid REFERENCES worker_bank_accounts(id),
    status varchar(50) DEFAULT 'Pending'
        CHECK (status IN ('Pending', 'Success', 'Failed', 'Cancelled')),
    admin_note text,
    held_release_at timestamptz,
    transaction_time timestamptz DEFAULT now()
);

-- ==========================================
-- 5. UTILITY
-- ==========================================

CREATE TABLE reviews (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id uuid UNIQUE REFERENCES bookings(id),
    customer_id uuid REFERENCES customers(customer_id),
    rating int CHECK (rating >= 1 AND rating <= 5),
    reason_tag varchar(100),
    comment text,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE notifications (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES users(id),
    title varchar(255),
    content text,
    is_read boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE user_devices (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES users(id),
    device_token varchar(255) NOT NULL,
    device_os varchar(20)
        CHECK (device_os IN ('iOS', 'Android')),
    last_active timestamptz
);

-- ==========================================
-- UPLOAD FILES
-- Bảng trung gian quản lý vòng đời upload ảnh/file
-- ==========================================

CREATE TABLE uploaded_files (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

    -- User nào tạo upload này
    owner_user_id uuid NOT NULL REFERENCES users(id),

    -- Upload dùng cho mục đích gì
    purpose varchar(50) NOT NULL
        CHECK (
            purpose IN (
                'AVATAR',
                'WORKER_KYC_FRONT',
                'WORKER_KYC_BACK',
                'WORKER_CERTIFICATE',
                'BOOKING_ISSUE_IMAGE',
                'PROOF_BEFORE_REPAIR',
                'PROOF_AFTER_REPAIR',
                'CHAT_IMAGE',
                'COMPLAINT_EVIDENCE'
            )
        ),

    -- Thông tin file gốc
    original_file_name varchar(255),
    content_type varchar(100) NOT NULL,
    file_size bigint NOT NULL CHECK (file_size > 0),

    -- Provider lưu trữ: MVP có thể dùng CLOUDINARY
    storage_provider varchar(30) NOT NULL DEFAULT 'CLOUDINARY'
        CHECK (storage_provider IN ('CLOUDINARY', 'S3', 'LOCAL')),

    -- Với Cloudinary: object_key có thể hiểu là public_id
    -- Với S3: object_key là key/path trong bucket
    object_key text NOT NULL UNIQUE,

    -- URL public/secure để app hiển thị ảnh
    file_url text NOT NULL,

    -- Trạng thái vòng đời upload
    status varchar(30) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'CONFIRMED', 'EXPIRED', 'FAILED')),

    -- File này đã được gắn vào nghiệp vụ nào chưa
    -- Ví dụ: USER_AVATAR, WORKER_KYC, PROOF_OF_WORK, CHAT_MESSAGE, COMPLAINT
    linked_entity_type varchar(50),

    -- UUID của bản ghi nghiệp vụ, ví dụ booking_id, complaint_id, user_id
    linked_entity_id uuid,

    -- Thời gian
    expires_at timestamptz,
    confirmed_at timestamptz,
    used_at timestamptz,
    created_at timestamptz DEFAULT now(),

    -- Không cho file_size quá lớn ở DB-level nếu muốn.
    -- Ví dụ giới hạn 10MB = 10485760 bytes.
    CHECK (file_size <= 10485760)
);

CREATE INDEX idx_uploaded_files_owner_user_id
    ON uploaded_files(owner_user_id);

CREATE INDEX idx_uploaded_files_purpose
    ON uploaded_files(purpose);

CREATE INDEX idx_uploaded_files_status
    ON uploaded_files(status);

CREATE INDEX idx_uploaded_files_created_at
    ON uploaded_files(created_at);

CREATE INDEX idx_uploaded_files_linked_entity
    ON uploaded_files(linked_entity_type, linked_entity_id);

-- ==========================================
-- INDEXES FOR FOREIGN KEYS
-- ==========================================

CREATE INDEX idx_user_social_logins_user_id ON user_social_logins(user_id);
CREATE INDEX idx_worker_identity_cards_worker_id ON worker_identity_cards(worker_id);
CREATE INDEX idx_customer_addresses_customer_id ON customer_addresses(customer_id);
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);

CREATE INDEX idx_service_items_category_id ON service_items(service_category_id);
CREATE INDEX idx_worker_services_worker_id ON worker_services(worker_id);
CREATE INDEX idx_worker_services_service_id ON worker_services(service_id);
CREATE INDEX idx_favorite_workers_customer_id ON favorite_workers(customer_id);
CREATE INDEX idx_favorite_workers_worker_id ON favorite_workers(worker_id);

CREATE INDEX idx_bookings_customer_id ON bookings(customer_id);
CREATE INDEX idx_bookings_worker_id ON bookings(worker_id);
CREATE INDEX idx_bookings_service_id ON bookings(service_id);
CREATE INDEX idx_bookings_status ON bookings(status);

CREATE INDEX idx_booking_worker_assignments_booking_id ON booking_worker_assignments(booking_id);
CREATE INDEX idx_booking_worker_assignments_worker_id ON booking_worker_assignments(worker_id);

CREATE INDEX idx_worker_quotations_worker_id ON worker_quotations(worker_id);
CREATE INDEX idx_worker_quotations_booking_id ON worker_quotations(booking_id);

CREATE INDEX idx_quotation_items_quotation_id ON quotation_items(quotation_id);
CREATE INDEX idx_quotation_items_service_item_id ON quotation_items(service_item_id);

CREATE INDEX idx_proof_of_works_booking_id ON proof_of_works(booking_id);
CREATE INDEX idx_booking_histories_booking_id ON booking_histories(booking_id);
CREATE INDEX idx_transaction_histories_wallet_id ON transaction_histories(wallet_id);
CREATE INDEX idx_transaction_histories_booking_id ON transaction_histories(booking_id);
CREATE INDEX idx_worker_bank_accounts_worker_id ON worker_bank_accounts(worker_id);
CREATE INDEX idx_reviews_customer_id ON reviews(customer_id);
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_user_devices_user_id ON user_devices(user_id);

COMMIT;