# B?t bu?c: Kích ho?t h? tr? AndroidX cho toàn b? d? án
android.useAndroidX=true

# Khuyên dùng: T? ??ng biên d?ch (migrate) các th? vi?n Support Library c? sang AndroidX
android.enableJetifier=true

# T?i ?u thêm b? nh? cho JVM Daemon ?? build m??t h?n (tu? ch?n)
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8