# backend/src/main/resources/application.yml
spring:
  application:
    name: fixit-backend

  profiles:
    active: dev

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

  data:
    mongodb:
      uri: mongodb://localhost:27017/fixit_chat_db

server:
  port: 8080
  servlet:
    context-path: /

# JWT configuration
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970} # 256-bit key
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days
